[build]
  command = "make netlify"
  functions = "functions"
  publish = "site"

[build.environment]
  GOBIN = "/opt/build/repo/functions"

[template.environment]
  GO_IMPORT_PATH = "github.com/aytdm/fuel-reproduction-api"
